# Generated by Django 4.2.4 on 2024-01-04 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory',
            name='task',
        ),
    ]
