# Generated by Django 4.2.4 on 2024-01-14 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_file_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
    ]
