# Generated by Django 4.2.4 on 2024-01-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_price',
            field=models.IntegerField(default=0),
        ),
    ]
