# Generated by Django 4.2.4 on 2024-01-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('car', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ManyToManyField(to='categories.category'),
        ),
    ]
