# Generated by Django 4.2.4 on 2024-01-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_remove_car_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_detail',
            field=models.TextField(default='hi'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_quentiry',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
