# Generated by Django 4.2.6 on 2024-01-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_car',
            old_name='category',
            new_name='Brand_Name',
        ),
        migrations.RenameField(
            model_name='all_car',
            old_name='car_detials',
            new_name='Car_Details',
        ),
        migrations.RenameField(
            model_name='all_car',
            old_name='carmodel',
            new_name='Car_Model',
        ),
    ]
