# Generated by Django 4.2.6 on 2024-01-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('third_app', '0002_rename_category_all_car_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
