# Generated by Django 4.2.6 on 2024-01-10 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserSite', '0002_postmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
        migrations.DeleteModel(
            name='PostModel',
        ),
    ]
