# Generated by Django 4.2.6 on 2024-01-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserSite', '0005_categorymodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
